// Mock data for demo purposes — used when Supabase tables are empty.
// All IDs are stable strings to allow cross-reference between entities.

export const MOCK_VENDOR = {
  id: "vendor-001",
  auth_user_id: "auth-001",
  phone: "9830012345",
  business_name: "Roy Travels",
  owner_name: "Rajesh Roy",
  city: "Kolkata",
  is_self_driver: false,
  onboarding_status: "active",
  overall_rating: 4.6,
  total_trips: 312,
};

export const MOCK_VEHICLES = [
  {
    id: "vehicle-001",
    vendor_id: "vendor-001",
    registration_number: "WB06AK5521",
    vehicle_category_id: "cat-sedan",
    make: "Maruti Suzuki",
    model: "Dzire",
    year: 2022,
    status: "active",
    condition_score: 8.4,
    insurance_expiry: "2025-08-15",
    fitness_expiry: "2025-11-20",
    puc_expiry: "2025-05-10",
    category_name: "Sedan",
    docs_verified: 4,
    docs_total: 5,
  },
  {
    id: "vehicle-002",
    vendor_id: "vendor-001",
    registration_number: "WB06BJ3302",
    vehicle_category_id: "cat-suv",
    make: "Toyota",
    model: "Innova Crysta",
    year: 2021,
    status: "active",
    condition_score: 9.1,
    insurance_expiry: "2026-02-28",
    fitness_expiry: "2026-05-15",
    puc_expiry: "2025-07-22",
    category_name: "SUV",
    docs_verified: 5,
    docs_total: 5,
  },
  {
    id: "vehicle-003",
    vendor_id: "vendor-001",
    registration_number: "WB06DM7788",
    vehicle_category_id: "cat-sedan",
    make: "Honda",
    model: "Amaze",
    year: 2020,
    status: "suspended",
    condition_score: 6.2,
    insurance_expiry: "2025-04-30",
    fitness_expiry: "2025-06-10",
    puc_expiry: "2025-03-15",
    category_name: "Sedan",
    docs_verified: 2,
    docs_total: 5,
  },
];

export const MOCK_DRIVERS = [
  {
    id: "driver-001",
    vendor_id: "vendor-001",
    name: "Suresh Mondal",
    phone: "9831100001",
    license_expiry: "2027-03-12",
    status: "active",
    overall_rating: 4.8,
    total_trips: 145,
    on_time_percentage: 96,
    assigned_vehicles: ["WB06AK5521"],
  },
  {
    id: "driver-002",
    vendor_id: "vendor-001",
    name: "Biplob Das",
    phone: "9831200002",
    license_expiry: "2025-05-18",
    status: "active",
    overall_rating: 4.5,
    total_trips: 98,
    on_time_percentage: 91,
    assigned_vehicles: ["WB06BJ3302"],
  },
  {
    id: "driver-003",
    vendor_id: "vendor-001",
    name: "Rajan Sharma",
    phone: "9831300003",
    license_expiry: "2026-09-01",
    status: "active",
    overall_rating: 4.3,
    total_trips: 52,
    on_time_percentage: 88,
    assigned_vehicles: ["WB06BJ3302"],
  },
  {
    id: "driver-004",
    vendor_id: "vendor-001",
    name: "Pintu Ghosh",
    phone: "9831400004",
    license_expiry: "2025-05-25",
    status: "inactive",
    overall_rating: 3.9,
    total_trips: 17,
    on_time_percentage: 79,
    assigned_vehicles: [],
  },
];

export const MOCK_BOOKINGS = [
  {
    id: "booking-001",
    booking_number: "AC-2604-0001",
    trip_type: "outstation",
    pickup_location: "Kolkata Airport",
    drop_location: "Digha Beach Resort",
    pickup_datetime: "2026-04-26T08:00:00",
    vehicle_category_id: "cat-sedan",
    vehicle_category_name: "Sedan",
    total_fare: 4200,
    advance_amount: 1000,
    status: "confirmed",
    assigned_vendor_id: "vendor-001",
    assigned_driver_id: "driver-001",
    assigned_driver_name: "Suresh Mondal",
    assigned_vehicle_id: "vehicle-001",
    assigned_vehicle_reg: "WB06AK5521",
    vendor_payout: 3360,
  },
  {
    id: "booking-002",
    booking_number: "AC-2604-0002",
    trip_type: "local",
    pickup_location: "Salt Lake Sector V",
    drop_location: "Howrah Station",
    pickup_datetime: "2026-04-24T14:30:00",
    vehicle_category_id: "cat-sedan",
    vehicle_category_name: "Sedan",
    total_fare: 650,
    advance_amount: 0,
    status: "completed",
    assigned_vendor_id: "vendor-001",
    assigned_driver_id: "driver-001",
    assigned_driver_name: "Suresh Mondal",
    assigned_vehicle_id: "vehicle-001",
    assigned_vehicle_reg: "WB06AK5521",
    vendor_payout: 520,
  },
  {
    id: "booking-003",
    booking_number: "AC-2604-0003",
    trip_type: "outstation",
    pickup_location: "Park Street, Kolkata",
    drop_location: "Shantiniketan",
    pickup_datetime: "2026-04-28T06:00:00",
    vehicle_category_id: "cat-suv",
    vehicle_category_name: "SUV",
    total_fare: 5800,
    advance_amount: 2000,
    status: "new",
    assigned_vendor_id: "vendor-001",
    assigned_driver_id: null,
    assigned_driver_name: null,
    assigned_vehicle_id: null,
    assigned_vehicle_reg: null,
    vendor_payout: 4640,
  },
  {
    id: "booking-004",
    booking_number: "AC-2304-0004",
    trip_type: "local",
    pickup_location: "New Town Action Area 1",
    drop_location: "NSCBI Airport",
    pickup_datetime: "2026-04-23T05:00:00",
    vehicle_category_id: "cat-sedan",
    vehicle_category_name: "Sedan",
    total_fare: 900,
    advance_amount: 0,
    status: "completed",
    assigned_vendor_id: "vendor-001",
    assigned_driver_id: "driver-002",
    assigned_driver_name: "Biplob Das",
    assigned_vehicle_id: "vehicle-002",
    assigned_vehicle_reg: "WB06BJ3302",
    vendor_payout: 720,
  },
  {
    id: "booking-005",
    booking_number: "AC-2504-0005",
    trip_type: "outstation",
    pickup_location: "Esplanade, Kolkata",
    drop_location: "Mandarmani Beach",
    pickup_datetime: "2026-04-25T07:00:00",
    vehicle_category_id: "cat-suv",
    vehicle_category_name: "SUV",
    total_fare: 6500,
    advance_amount: 2500,
    status: "new",
    assigned_vendor_id: "vendor-001",
    assigned_driver_id: null,
    assigned_driver_name: null,
    assigned_vehicle_id: null,
    assigned_vehicle_reg: null,
    vendor_payout: 5200,
  },
];

export const MOCK_EARNINGS = {
  current_month: {
    label: "April 2026",
    total_fare: 17050,
    commission_amount: 3410,
    vendor_payout: 13640,
    pending_payout: 4640,
    paid_payout: 9000,
  },
  last_month: {
    label: "March 2026",
    total_fare: 24300,
    commission_amount: 4860,
    vendor_payout: 19440,
    pending_payout: 0,
    paid_payout: 19440,
  },
  last_3_months: {
    label: "Feb – Apr 2026",
    total_fare: 58200,
    commission_amount: 11640,
    vendor_payout: 46560,
    pending_payout: 4640,
    paid_payout: 41920,
  },
};

export const MOCK_EARNINGS_ROWS = [
  {
    id: "earn-001",
    booking_id: "booking-002",
    booking_number: "AC-2604-0002",
    date: "2026-04-24",
    route: "Salt Lake → Howrah",
    total_fare: 650,
    commission_rate: 20,
    commission_amount: 130,
    vendor_payout: 520,
    payout_status: "paid",
  },
  {
    id: "earn-002",
    booking_id: "booking-004",
    booking_number: "AC-2304-0004",
    date: "2026-04-23",
    route: "New Town → Airport",
    total_fare: 900,
    commission_rate: 20,
    commission_amount: 180,
    vendor_payout: 720,
    payout_status: "paid",
  },
  {
    id: "earn-003",
    booking_id: "booking-001",
    booking_number: "AC-2604-0001",
    date: "2026-04-26",
    route: "Kolkata Airport → Digha",
    total_fare: 4200,
    commission_rate: 20,
    commission_amount: 840,
    vendor_payout: 3360,
    payout_status: "processing",
  },
  {
    id: "earn-004",
    booking_id: "booking-003",
    booking_number: "AC-2604-0003",
    date: "2026-04-28",
    route: "Park Street → Shantiniketan",
    total_fare: 5800,
    commission_rate: 20,
    commission_amount: 1160,
    vendor_payout: 4640,
    payout_status: "pending",
  },
  {
    id: "earn-005",
    booking_id: "booking-005",
    booking_number: "AC-2504-0005",
    date: "2026-04-25",
    route: "Esplanade → Mandarmani",
    total_fare: 6500,
    commission_rate: 20,
    commission_amount: 1300,
    vendor_payout: 5200,
    payout_status: "pending",
  },
];

export const MOCK_ALERTS = [
  {
    type: "driver_license",
    entity: "driver-002",
    entity_name: "Biplob Das",
    message: "Driving license expires in 24 days",
    daysUntilExpiry: 24,
    link: "/dashboard/fleet/drivers/driver-002",
  },
  {
    type: "driver_license",
    entity: "driver-004",
    entity_name: "Pintu Ghosh",
    message: "Driving license expires in 31 days",
    daysUntilExpiry: 31,
    link: "/dashboard/fleet/drivers/driver-004",
  },
  {
    type: "vehicle_insurance",
    entity: "vehicle-003",
    entity_name: "WB06DM7788",
    message: "Insurance expired 6 days ago",
    daysUntilExpiry: -6,
    link: "/dashboard/fleet/vehicles/vehicle-003",
  },
  {
    type: "vehicle_puc",
    entity: "vehicle-001",
    entity_name: "WB06AK5521",
    message: "PUC certificate expires in 16 days",
    daysUntilExpiry: 16,
    link: "/dashboard/fleet/vehicles/vehicle-001",
  },
];
