"use client";

import { useState, useEffect } from "react";
import { IndianRupee, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getVendorEarnings, type EarningRow, type EarningsSummary } from "@/lib/vendor";
import { cn } from "@/lib/utils";

const DEMO_VENDOR_ID = "vendor-001";

type Period = "this_month" | "last_month" | "last_3_months";

const PERIODS: { key: Period; label: string }[] = [
  { key: "this_month", label: "This Month" },
  { key: "last_month", label: "Last Month" },
  { key: "last_3_months", label: "Last 3 Months" },
];

function PayoutStatusBadge({ status }: { status: string }) {
  const map: Record<string, string> = {
    pending: "bg-yellow-100 text-yellow-700",
    processing: "bg-blue-100 text-blue-700",
    paid: "bg-green-100 text-green-700",
  };
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium capitalize ${map[status] ?? "bg-gray-100 text-gray-600"}`}
    >
      {status}
    </span>
  );
}

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(n);
}

function formatDate(dt: string) {
  return new Date(dt).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function downloadStatement(
  summary: EarningsSummary,
  rows: EarningRow[]
): void {
  const lines = [
    "AaoCab Vendor Earnings Statement",
    "=".repeat(40),
    `Period: ${summary.label}`,
    "",
    `Total Fare Collected : Rs. ${formatCurrency(summary.total_fare)}`,
    `Commission (20%)     : Rs. ${formatCurrency(summary.commission_amount)}`,
    `Net Payout           : Rs. ${formatCurrency(summary.vendor_payout)}`,
    `Pending              : Rs. ${formatCurrency(summary.pending_payout)}`,
    `Paid                 : Rs. ${formatCurrency(summary.paid_payout)}`,
    "",
    "Trip Breakdown",
    "-".repeat(40),
    ...rows.map(
      (r) =>
        `${formatDate(r.date)} | ${r.booking_number} | ${r.route} | Rs. ${formatCurrency(r.vendor_payout)} | ${r.payout_status}`
    ),
    "",
    "Generated by AaoCab Vendor Portal",
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `aaocab-earnings-${summary.label.replace(/\s/g, "-")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function EarningsPage() {
  const [period, setPeriod] = useState<Period>("this_month");
  const [summary, setSummary] = useState<EarningsSummary | null>(null);
  const [rows, setRows] = useState<EarningRow[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    getVendorEarnings(DEMO_VENDOR_ID, period).then(({ summary: s, rows: r }) => {
      setSummary(s);
      setRows(r);
      setLoading(false);
    });
  }, [period]);

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <h1 className="font-heading text-xl font-bold text-foreground">
          Earnings
        </h1>
        {summary && (
          <Button
            variant="outline"
            size="sm"
            className="flex items-center gap-1.5 cursor-pointer transition-all duration-200"
            onClick={() => downloadStatement(summary, rows)}
          >
            <Download className="size-3.5" />
            Download Statement
          </Button>
        )}
      </div>

      {/* Period selector */}
      <div className="flex gap-1 rounded-xl bg-white border border-border p-1 w-fit">
        {PERIODS.map((p) => (
          <button
            key={p.key}
            onClick={() => setPeriod(p.key)}
            className={cn(
              "rounded-lg px-3 py-2 text-sm font-medium transition-all duration-200 cursor-pointer whitespace-nowrap",
              period === p.key
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            {p.label}
          </button>
        ))}
      </div>

      {loading || !summary ? (
        <div className="py-12 text-center text-sm text-muted-foreground">
          Loading earnings...
        </div>
      ) : (
        <>
          {/* Summary cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="col-span-2 sm:col-span-1 rounded-xl bg-white border border-border p-5">
              <div className="flex items-center gap-2 mb-2">
                <div className="flex size-8 items-center justify-center rounded-lg bg-[#E6F7F5]">
                  <IndianRupee className="size-4 text-accent" />
                </div>
                <p className="text-xs text-muted-foreground">Total Earned</p>
              </div>
              <p className="font-heading text-2xl font-bold text-foreground">
                ₹{formatCurrency(summary.total_fare)}
              </p>
            </div>

            <div className="rounded-xl bg-white border border-border p-5">
              <p className="text-xs text-muted-foreground mb-1">
                Commission Deducted
              </p>
              <p className="font-heading text-xl font-semibold text-destructive">
                -₹{formatCurrency(summary.commission_amount)}
              </p>
              <p className="text-xs text-muted-foreground mt-0.5">20%</p>
            </div>

            <div className="rounded-xl bg-[#E6F7F5] border border-[#C0EAE5] p-5">
              <p className="text-xs text-accent font-medium mb-1">Net Payout</p>
              <p className="font-heading text-xl font-bold text-accent">
                ₹{formatCurrency(summary.vendor_payout)}
              </p>
            </div>

            <div className="rounded-xl bg-amber-50 border border-amber-200 p-5">
              <p className="text-xs text-amber-700 mb-1">Pending Payout</p>
              <p className="font-heading text-xl font-bold text-amber-700">
                ₹{formatCurrency(summary.pending_payout)}
              </p>
            </div>
          </div>

          {/* Per-trip breakdown */}
          <section>
            <h2 className="font-heading text-base font-semibold text-foreground mb-3">
              Trip Breakdown
            </h2>

            {/* Desktop table */}
            <div className="hidden sm:block rounded-xl bg-white border border-border overflow-hidden">
              <table className="w-full text-sm">
                <thead className="border-b border-border">
                  <tr className="text-left">
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground">
                      Date
                    </th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground">
                      Booking
                    </th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground">
                      Route
                    </th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground text-right">
                      Fare
                    </th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground text-right">
                      Commission
                    </th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground text-right">
                      Payout
                    </th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground">
                      Status
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {rows.map((row) => (
                    <tr key={row.id} className="hover:bg-muted transition-colors">
                      <td className="px-4 py-3 text-xs text-muted-foreground whitespace-nowrap">
                        {formatDate(row.date)}
                      </td>
                      <td className="px-4 py-3 font-mono text-xs text-muted-foreground">
                        {row.booking_number}
                      </td>
                      <td className="px-4 py-3 text-sm text-foreground max-w-[160px] truncate">
                        {row.route}
                      </td>
                      <td className="px-4 py-3 text-sm text-right font-medium">
                        ₹{formatCurrency(row.total_fare)}
                      </td>
                      <td className="px-4 py-3 text-sm text-right text-destructive">
                        -₹{formatCurrency(row.commission_amount)}
                      </td>
                      <td className="px-4 py-3 text-sm text-right font-semibold text-accent">
                        ₹{formatCurrency(row.vendor_payout)}
                      </td>
                      <td className="px-4 py-3">
                        <PayoutStatusBadge status={row.payout_status} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Mobile cards */}
            <div className="sm:hidden flex flex-col gap-2">
              {rows.map((row) => (
                <div
                  key={row.id}
                  className="rounded-xl bg-white border border-border p-4 flex flex-col gap-2"
                >
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="font-mono text-xs text-muted-foreground">
                        {row.booking_number}
                      </p>
                      <p className="text-sm font-medium text-foreground">
                        {row.route}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {formatDate(row.date)}
                      </p>
                    </div>
                    <PayoutStatusBadge status={row.payout_status} />
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Fare</span>
                    <span className="font-medium">₹{formatCurrency(row.total_fare)}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Commission (20%)</span>
                    <span className="text-destructive">-₹{formatCurrency(row.commission_amount)}</span>
                  </div>
                  <div className="flex justify-between text-sm border-t border-border pt-2">
                    <span className="font-medium">Your Payout</span>
                    <span className="font-bold text-accent">₹{formatCurrency(row.vendor_payout)}</span>
                  </div>
                </div>
              ))}
            </div>

            {rows.length === 0 && (
              <p className="text-center text-sm text-muted-foreground py-12">
                No earnings data for this period.
              </p>
            )}
          </section>
        </>
      )}
    </div>
  );
}
